# fly.toml app configuration file generated for whatsupdoc on 2023-12-16T15:24:54+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "whatsupdoc"
primary_region = "nrt"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8501"

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
